PREFIX mass: <https://w3id.org/mass-ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?vessel ?mode
WHERE {
  ?vessel a/rdfs:subClassOf* mass:MASSVessel ;
          mass:hasOperationalMode ?mode .
}
ORDER BY ?vessel ?mode
